[package]
name = "fast_vless"
version = "0.0.1"
authors = ["https://github.com/firewallPass"]
edition = "2021"
license = "MIT"
description = "Fast vless client/server implementation written in Rust async/.await (tokio)"
repository = "https://github.com/firewallPass/fast-vless"
categories = [
    "asynchronous",
    "network-programming",
    "command-line-utilities",
    "authentication",
]
keywords = ["io", "proxy", "vpn", "async", "socks"]

[features]
default = []
socks4 = []

[dependencies]
log = "0.4"
tokio = { version = "1", features = ["io-util", "net", "time", "macros"] }
anyhow = "1"
thiserror = "1"
tokio-stream = "0.1"
async-trait = "0.1"
socket2 = "0.5.8"

# Dependencies for examples and tests
[dev-dependencies]
env_logger = "0.9"
structopt = "0.3"
tokio = { version = "1", features = [
    "io-util",
    "net",
    "time",
    "rt-multi-thread",
    "macros",
] }
tokio-test = "0.4"

[[example]]
name = "server"

[[example]]
name = "client"

[[example]]
name = "custom_auth_server"

[[example]]
name = "router"
